package iqrahospital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author shada
 */
public class Dentist extends javax.swing.JFrame {

    /**
     * Creates new form FirstScreen
     */
    int mrNumber;
    public Dentist(int mrNumber) {
        initComponents();
        this.mrNumber = mrNumber;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Dentist1 = new javax.swing.JRadioButton();
        Dentist2 = new javax.swing.JRadioButton();
        Dentist3 = new javax.swing.JRadioButton();
        Dentist4 = new javax.swing.JRadioButton();
        Dentist5 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME TO IQRA HOSPITAL!");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 249, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 6));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IQRA HOSPITAL");
        jLabel1.setAlignmentX(1.0F);
        jLabel1.setAlignmentY(1.0F);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel2.setText("DENTIST");

        btnNext.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnNext.setText("Next →");
        btnNext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnBack.setText("← Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 17)); // NOI18N
        jLabel5.setText("These doctors are available (Select any one)");

        Dentist1.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Dentist1);
        Dentist1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Dentist1.setText("Dr. Ismail Ahmed");
        Dentist1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dentist1ActionPerformed(evt);
            }
        });

        Dentist2.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Dentist2);
        Dentist2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Dentist2.setText("Dr. Haider Zaman");
        Dentist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dentist2ActionPerformed(evt);
            }
        });

        Dentist3.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Dentist3);
        Dentist3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Dentist3.setText("Dr. Arif Khan");

        Dentist4.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Dentist4);
        Dentist4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Dentist4.setText("Dr. Wahab ");
        Dentist4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dentist4ActionPerformed(evt);
            }
        });

        Dentist5.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Dentist5);
        Dentist5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Dentist5.setText("Dr. Ayesha Ahmed");
        Dentist5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dentist5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Version 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(Dentist1)
                            .addComponent(Dentist2)
                            .addComponent(Dentist3)
                            .addComponent(Dentist4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Dentist5)
                                .addGap(178, 178, 178))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dentist1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dentist2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dentist3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dentist4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dentist5)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String dentist = null;
        if(Dentist1.isSelected()){
            Timeslot ts1 = new Timeslot(mrNumber);
            ts1.setVisible(true);
            this.setVisible(false);
            dentist = "Dr. Ismail Ahmed";
        }
        else if(Dentist2.isSelected()){
            Timeslot ts2 = new Timeslot(mrNumber);
            ts2.setVisible(true);
            this.setVisible(false);
            dentist = "Dr. Haider Zaman";
        }
        else if(Dentist3.isSelected()){
            Timeslot ts3 = new Timeslot(mrNumber);
            ts3.setVisible(true);
            this.setVisible(false);
            dentist = "Dr. Arif Khan";
        }
        else if(Dentist4.isSelected()){
            Timeslot ts4 = new Timeslot(mrNumber);
            ts4.setVisible(true);
            this.setVisible(false);
            dentist = "Dr. Wahab ";
        }
        else if  (Dentist5.isSelected()){
            Timeslot ts5 = new Timeslot(mrNumber);
            ts5.setVisible(true);
            this.setVisible(false);
            dentist = "Dr. Ayesha Ahmed";
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid Selection!");
        }
        
        //DATABASE
        try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");
                String updateStatement = "UPDATE patientdata SET doctor = ? WHERE mrNumber = ?";
                PreparedStatement ptst = conn.prepareStatement(updateStatement);

                ptst.setString(1, dentist);
                ptst.setInt(2    , mrNumber);
                ptst.executeUpdate();
                
                conn.close();
               

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Something went wrong! Try again later");
            }
        
       
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ThirdScreen ts = new ThirdScreen();
        ts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void Dentist4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dentist4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dentist4ActionPerformed

    private void Dentist5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dentist5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dentist5ActionPerformed

    private void Dentist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dentist2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dentist2ActionPerformed

    private void Dentist1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dentist1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dentist1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Dentist1;
    private javax.swing.JRadioButton Dentist2;
    private javax.swing.JRadioButton Dentist3;
    private javax.swing.JRadioButton Dentist4;
    private javax.swing.JRadioButton Dentist5;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
