package iqrahospital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author shada
 */
public class Neurologists extends javax.swing.JFrame {

    /**
     * Creates new form FirstScreen
     */
    int mrNumber;
    public Neurologists(int mrNumber) {
        initComponents();
        this.mrNumber = mrNumber;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        neuro1 = new javax.swing.JRadioButton();
        neuro2 = new javax.swing.JRadioButton();
        neuro3 = new javax.swing.JRadioButton();
        neuro4 = new javax.swing.JRadioButton();
        neuro5 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME TO IQRA HOSPITAL!");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 249, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 6));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IQRA HOSPITAL");
        jLabel1.setAlignmentX(1.0F);
        jLabel1.setAlignmentY(1.0F);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel2.setText("NEUROLOGISTS");

        btnNext.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnNext.setText("Next →");
        btnNext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnBack.setText("← Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 17)); // NOI18N
        jLabel5.setText("These doctors are available (Select any one)");

        neuro1.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(neuro1);
        neuro1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        neuro1.setText("Dr. Gulzar Ahmed");
        neuro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neuro1ActionPerformed(evt);
            }
        });

        neuro2.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(neuro2);
        neuro2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        neuro2.setText("Dr. Nasir jamal");
        neuro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neuro2ActionPerformed(evt);
            }
        });

        neuro3.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(neuro3);
        neuro3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        neuro3.setText("Dr. Yusuf Firoz");

        neuro4.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(neuro4);
        neuro4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        neuro4.setText("Dr. Asma Qaiser");
        neuro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neuro4ActionPerformed(evt);
            }
        });

        neuro5.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(neuro5);
        neuro5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        neuro5.setText("Dr. Faiza Naseem");
        neuro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neuro5ActionPerformed(evt);
            }
        });

        jLabel7.setText("Version 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(neuro1)
                            .addComponent(jLabel5)
                            .addComponent(neuro2)
                            .addComponent(neuro3)
                            .addComponent(neuro4)
                            .addComponent(neuro5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neuro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neuro2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neuro3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neuro4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neuro5)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       String neuroDoctor = null;
       
        if(neuro1.isSelected()){
            Timeslot ts1 = new Timeslot(mrNumber);
            ts1.setVisible(true);
            this.setVisible(false);
            neuroDoctor ="Dr. Gulzar Ahmed";
        }
        else if(neuro2.isSelected()){
            Timeslot ts2 = new Timeslot(mrNumber);
            ts2.setVisible(true);
            this.setVisible(false);
            neuroDoctor ="Dr. Nasir jamal";
        }
        else if(neuro3.isSelected()){
            Timeslot ts3 = new Timeslot(mrNumber);
            ts3.setVisible(true);
            this.setVisible(false);
            neuroDoctor ="Dr. Yusuf Firoz";
        }
        else if(neuro4.isSelected()){
            Timeslot ts4 = new Timeslot(mrNumber);
            ts4.setVisible(true);
            this.setVisible(false);
            neuroDoctor ="Dr. Asma Qaiser";
        }
        else if  (neuro5.isSelected()){
            Timeslot ts5 = new Timeslot(mrNumber);
            ts5.setVisible(true);
            this.setVisible(false);
            neuroDoctor ="Dr. Faiza Naseem";
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid Selection!");
        }
        
        //DATABASE
        try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");
                String updateStatement = "UPDATE patientdata SET doctor = ? WHERE mrNumber = ?";
                PreparedStatement ptst = conn.prepareStatement(updateStatement);

                ptst.setString(1, neuroDoctor);
                ptst.setInt(2    , mrNumber);
                ptst.executeUpdate();
                
                conn.close();
               

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Something went wrong! Try again later");
            }
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ThirdScreen ts = new ThirdScreen();
        ts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void neuro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neuro4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neuro4ActionPerformed

    private void neuro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neuro5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neuro5ActionPerformed

    private void neuro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neuro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neuro2ActionPerformed

    private void neuro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neuro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neuro1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton neuro1;
    private javax.swing.JRadioButton neuro2;
    private javax.swing.JRadioButton neuro3;
    private javax.swing.JRadioButton neuro4;
    private javax.swing.JRadioButton neuro5;
    // End of variables declaration//GEN-END:variables
}
