package iqrahospital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author shada
 */
public class Physician extends javax.swing.JFrame {

    /**
     * Creates new form FirstScreen
     */
    int mrNumber;
    public Physician(int mrNumber) {
        initComponents();
        this.mrNumber = mrNumber;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Physician1 = new javax.swing.JRadioButton();
        Physician2 = new javax.swing.JRadioButton();
        Physician3 = new javax.swing.JRadioButton();
        Physician4 = new javax.swing.JRadioButton();
        Physician5 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setText("Version 1.0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME TO IQRA HOSPITAL!");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 249, 246));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 6, true));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IQRA HOSPITAL");
        jLabel1.setAlignmentX(1.0F);
        jLabel1.setAlignmentY(1.0F);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel2.setText("PHYSICIAN");

        btnNext.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnNext.setText("Next →");
        btnNext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnBack.setText("← Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 17)); // NOI18N
        jLabel5.setText("These doctors are available (Select any one)");

        Physician1.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Physician1);
        Physician1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Physician1.setText("Dr. Ali Akhbar");
        Physician1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Physician1ActionPerformed(evt);
            }
        });

        Physician2.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Physician2);
        Physician2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Physician2.setText("Dr. Umair Ali");
        Physician2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Physician2ActionPerformed(evt);
            }
        });

        Physician3.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Physician3);
        Physician3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Physician3.setText("Dr. Imran ");

        Physician4.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Physician4);
        Physician4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Physician4.setText("Dr. Adnan");
        Physician4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Physician4ActionPerformed(evt);
            }
        });

        Physician5.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Physician5);
        Physician5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Physician5.setText("Dr. Ali khan");
        Physician5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Physician5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Version 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(Physician1)
                            .addComponent(Physician2)
                            .addComponent(Physician3)
                            .addComponent(Physician4)
                            .addComponent(Physician5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Physician1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Physician2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Physician3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Physician4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Physician5)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       String phyDoctor = null;
        if(Physician1.isSelected()){
            Timeslot ts1 = new Timeslot(mrNumber);
            ts1.setVisible(true);
            this.setVisible(false);
            phyDoctor = "Dr. Ali Akhbar";
        }
        else if(Physician2.isSelected()){
            Timeslot ts2 = new Timeslot(mrNumber);
            ts2.setVisible(true);
            this.setVisible(false);
             phyDoctor = "Dr. Umair Ali";
        }
        else if(Physician3.isSelected()){
            Timeslot ts3 = new Timeslot(mrNumber);
            ts3.setVisible(true);
            this.setVisible(false);
             phyDoctor = "Dr. Imran ";
        }
        else if(Physician4.isSelected()){
            Timeslot ts4 = new Timeslot(mrNumber);
            ts4.setVisible(true);
            this.setVisible(false);
             phyDoctor = "Dr. Adnan";
        }
        else if  (Physician5.isSelected()){
            Timeslot ts5 = new Timeslot(mrNumber);
            ts5.setVisible(true);
            this.setVisible(false);
             phyDoctor = "Dr. Ali khan";
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid Selection!");
        }
        
        //DATABASE
        try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");
                String updateStatement = "UPDATE patientdata SET doctor = ? WHERE mrNumber = ?";
                PreparedStatement ptst = conn.prepareStatement(updateStatement);

                ptst.setString(1, phyDoctor);
                ptst.setInt(2    , mrNumber);
                ptst.executeUpdate();
                
                conn.close();
               

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Something went wrong! Try again later");
            }
       
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ThirdScreen ts = new ThirdScreen();
        ts.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void Physician4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Physician4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Physician4ActionPerformed

    private void Physician5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Physician5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Physician5ActionPerformed

    private void Physician2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Physician2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Physician2ActionPerformed

    private void Physician1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Physician1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Physician1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Physician1;
    private javax.swing.JRadioButton Physician2;
    private javax.swing.JRadioButton Physician3;
    private javax.swing.JRadioButton Physician4;
    private javax.swing.JRadioButton Physician5;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
