package iqrahospital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author shada
 */
public class ThirdScreen extends javax.swing.JFrame {

    String name;
    int generatedId;
    
    public ThirdScreen() {
        initComponents();
    }

    public ThirdScreen(String name, int generatedId) {

        this.name = name;
        this.generatedId = generatedId;
        initComponents();
        label2.setText("Hi " + name + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup8 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Cardio = new javax.swing.JRadioButton();
        Neurology = new javax.swing.JRadioButton();
        Gynaecology = new javax.swing.JRadioButton();
        physician = new javax.swing.JRadioButton();
        denist = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("Version 1.0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME TO IQRA HOSPITAL!");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 249, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 6));
        jPanel1.setPreferredSize(new java.awt.Dimension(590, 400));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IQRA HOSPITAL");
        jLabel1.setAlignmentX(1.0F);
        jLabel1.setAlignmentY(1.0F);

        label2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        label2.setText("Hi, name!");

        btnNext.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnNext.setText("Next →");
        btnNext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnBack.setText("← Back");
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        jLabel5.setText("These Specialaity are available (Choose any one)");

        Cardio.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup8.add(Cardio);
        Cardio.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Cardio.setText("Cardiology");
        Cardio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardioActionPerformed(evt);
            }
        });

        Neurology.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup8.add(Neurology);
        Neurology.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Neurology.setText("Neurology");
        Neurology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeurologyActionPerformed(evt);
            }
        });

        Gynaecology.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup8.add(Gynaecology);
        Gynaecology.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Gynaecology.setText("Gynaecology");

        physician.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup8.add(physician);
        physician.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        physician.setText("General physician");
        physician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicianActionPerformed(evt);
            }
        });

        denist.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup8.add(denist);
        denist.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        denist.setText("Dentist");
        denist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denistActionPerformed(evt);
            }
        });

        jLabel7.setText("Version 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Cardio)
                    .addComponent(Neurology)
                    .addComponent(Gynaecology)
                    .addComponent(physician)
                    .addComponent(denist)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cardio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Neurology)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gynaecology)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(physician)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denist)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel7)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

         String speciality = "null";
        int mrNumber = generatedId;

        if (Cardio.isSelected()) {
            Cardiologist card = new Cardiologist(mrNumber);
            card.setVisible(true);
            this.setVisible(false);
            speciality = "Cardiologist";

        } else if (Neurology.isSelected()) {
            Neurologists neuro = new Neurologists(mrNumber);
            neuro.setVisible(true);
            this.setVisible(false);
            speciality = "Neurologist";
        } else if (denist.isSelected()) {
            Dentist den = new Dentist(mrNumber);
            den.setVisible(true);
            this.setVisible(false);
            speciality = "Dentist";
        } else if (physician.isSelected()) {
            Physician phy = new Physician(mrNumber);
            phy.setVisible(true);
            this.setVisible(false);
            speciality = "Physician";
        } else if (Gynaecology.isSelected()) {
            Gynaecologist gyn = new Gynaecologist(mrNumber);
            gyn.setVisible(true);
            this.setVisible(false);
            speciality = "Gynaecology";
        } else {
            JOptionPane.showMessageDialog(this, "Select any 1 Speciality");
        }
        
     

        try {
            
            //Set Driver Of SQL
            Class.forName("com.mysql.jdbc.Driver");
            
            //Set Connection with localhost server
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");
            
             // UPDATE Query of SQL using to get replace data on DB
            String updateStatement = "UPDATE patientdata SET speciality = ? WHERE mrNumber = ?";
            
            //PreparedStatement is used to execute SQL Queries
            PreparedStatement ptst = conn.prepareStatement(updateStatement);

            //Set parameter value where ? in SQL Query
            ptst.setString(1, speciality);
            ptst.setInt(2, mrNumber);
            ptst.executeUpdate();

            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong! Try again later");
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        SecondScreen ss = new SecondScreen();
        ss.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void physicianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_physicianActionPerformed

    private void denistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_denistActionPerformed

    private void CardioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardioActionPerformed

    }//GEN-LAST:event_CardioActionPerformed

    private void NeurologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeurologyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NeurologyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cardio;
    private javax.swing.JRadioButton Gynaecology;
    private javax.swing.JRadioButton Neurology;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JRadioButton denist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label2;
    private javax.swing.JRadioButton physician;
    // End of variables declaration//GEN-END:variables
}
