package iqrahospital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import iqrahospital.ThirdScreen;
import java.sql.ResultSet;

/**
 *
 * @author shada
 */
public class Timeslot extends javax.swing.JFrame {

    /**
     * Creates new form FirstScreen
     */
    int mrNumber;
    String Speciality;

    public Timeslot(int mrNumber) {
        initComponents();
        this.mrNumber = mrNumber;
    }

    public Timeslot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Timeslot1 = new javax.swing.JRadioButton();
        Timeslot2 = new javax.swing.JRadioButton();
        Timeslot3 = new javax.swing.JRadioButton();
        Timeslot4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME TO IQRA HOSPITAL!");
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 249, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 6));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IQRA HOSPITAL");
        jLabel1.setAlignmentX(1.0F);
        jLabel1.setAlignmentY(1.0F);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel2.setText("TIME SLOTS");

        btnNext.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnNext.setText("Next →");
        btnNext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnback.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        btnback.setText("← Back");
        btnback.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 17)); // NOI18N
        jLabel5.setText(" Doctor Availability Time (Select any one)");

        Timeslot1.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Timeslot1);
        Timeslot1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Timeslot1.setText("Monday  3:00 - 4:00 PM ");
        Timeslot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Timeslot1ActionPerformed(evt);
            }
        });

        Timeslot2.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Timeslot2);
        Timeslot2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Timeslot2.setText("Tuesday  2:30 - 4:30 PM ");
        Timeslot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Timeslot2ActionPerformed(evt);
            }
        });

        Timeslot3.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Timeslot3);
        Timeslot3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Timeslot3.setText("Friday  10:30 - 2:30 PM ");
        Timeslot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Timeslot3ActionPerformed(evt);
            }
        });

        Timeslot4.setBackground(new java.awt.Color(250, 249, 246));
        buttonGroup1.add(Timeslot4);
        Timeslot4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 15)); // NOI18N
        Timeslot4.setText("Saturday  10:30 - 2:30 PM ");
        Timeslot4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Timeslot4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Version 1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Timeslot1)
                            .addComponent(Timeslot3)
                            .addComponent(Timeslot4)
                            .addComponent(Timeslot2)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Timeslot1)
                .addGap(8, 8, 8)
                .addComponent(Timeslot2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Timeslot3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Timeslot4)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String timeSlot = null;
        if (Timeslot1.isSelected()) {
            Payment py = new Payment(mrNumber);
            py.setVisible(true);
            this.setVisible(false);
            timeSlot = "Monday  3:00 - 4:00 PM ";
        } else if (Timeslot2.isSelected()) {
            Payment py = new Payment(mrNumber);
            py.setVisible(true);
            this.setVisible(false);
            timeSlot = "Tuesday  2:30 - 4:30 PM ";
        } else if (Timeslot3.isSelected()) {
            Payment py = new Payment(mrNumber);
            py.setVisible(true);
            this.setVisible(false);
            timeSlot = "Friday  10:30 - 2:30 PM ";
        } else if (Timeslot4.isSelected()) {
            Payment py = new Payment(mrNumber);
            py.setVisible(true);
            this.setVisible(false);
            timeSlot = "Saturday  10:30 - 2:30 PM ";

        } else {
            JOptionPane.showMessageDialog(this, "Invalid Selection!");
        }

        //DATABASE
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");
            String updateStatement = "UPDATE patientdata SET timeSlot = ? WHERE mrNumber = ?";
            PreparedStatement ptst = conn.prepareStatement(updateStatement);

            ptst.setString(1, timeSlot);
            ptst.setInt(2, mrNumber);
            ptst.executeUpdate();

            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Something went wrong! Try again later");
        }

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
    String txtspeciality = "";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/iqrahospital", "root", "");

            // Retrieve the data using the unique ID
            String selectStatement = "SELECT * FROM patientdata WHERE mrNumber = ?";
            PreparedStatement stmt = conn.prepareStatement(selectStatement);
            stmt.setInt(1, mrNumber);
            ResultSet result = stmt.executeQuery();

            
            // Retrieve the first row of data
            if (result.next()) {
                txtspeciality = result.getString("speciality");
            }
        } catch (Exception e) {
            ThirdScreen ts = new ThirdScreen();
            ts.setVisible(true);
            this.setVisible(false);
        }
        

        if (txtspeciality.equals("Cardiologist")) {
            Cardiologist ca = new Cardiologist(mrNumber);
            ca.setVisible(true);
            dispose();
        } else if (txtspeciality.equals("Neurologist")) {
            Neurologists na = new Neurologists(mrNumber);
            na.setVisible(true);
            dispose();

        }
        else if (txtspeciality.equals("Dentist")) {
            Dentist da = new Dentist(mrNumber);
            da.setVisible(true);
            dispose();

        }
        else if (txtspeciality.equals("Physician")) {
            Physician pa = new Physician(mrNumber);
            pa.setVisible(true);
            dispose();

        }
        else if (txtspeciality.equals("Gynaecology")) {
            Gynaecologist ga = new Gynaecologist(mrNumber);
            ga.setVisible(true);
            dispose();

        }
        else{
        Cardiologist c = new Cardiologist(mrNumber);
        c.setVisible(true);
        this.setVisible(false);}
    }//GEN-LAST:event_btnbackActionPerformed

    private void Timeslot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Timeslot2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Timeslot2ActionPerformed

    private void Timeslot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Timeslot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Timeslot1ActionPerformed

    private void Timeslot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Timeslot3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Timeslot3ActionPerformed

    private void Timeslot4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Timeslot4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Timeslot4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Timeslot1;
    private javax.swing.JRadioButton Timeslot2;
    private javax.swing.JRadioButton Timeslot3;
    private javax.swing.JRadioButton Timeslot4;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnback;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
